routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('landing');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/landing', 'PagesController@landing');
Route::get('/dashboard', 'PagesController@dashboard');
Route::get('/dashboarda', 'PagesController@dashboarda');
Route::get('/dashboardw', 'PagesController@dashboardw')->name('dashboardw');
Route::get('/choose', 'PagesController@choose')->name('pilihSurat')->middleware('auth');

// SURAT
Route::resource('/surat', 'SuratController');
//WARGA
Route::resource('/warga', 'WargaController');
Route::get('/indexwarga', 'WargaController@indexwarga')->name('indexWarga');
//AGAMA
Route::resource('/agama', 'AgamaController');
//PEKERJAAN
Route::resource('/pkj', 'PekerjaanController');
//PENDIDIKAN
Route::resource('/pdd', 'PendidikanController');
//PETUGAS atau ADMIN
Route::resource('/petugas', 'PetugasController');
//IBU
Route::resource('/ibu', 'IbuController');
//AYAH
Route::resource('/ayah', 'AyahController');
//SUTRI
Route::resource('/sutri', 'SutriController');
//ANAK
Route::resource('/anak', 'AnakController');
//PERUSAHAAN
Route::resource('/psh', 'PerusahaanController');
//TAKLIM
Route::resource('/mjt', 'TaklimController');
//KEMATIAN
Route::resource('/kmt', 'KematianController');

//PEMBUATAN
//admin 
Route::post('/buat/{id}/verify', 'PembuatanController@verify')->name('verifyBuat');
Route::post('/buat/{id}/remove', 'PembuatanController@remove')->name('removeBuat');
Route::get('/pending', 'PembuatanController@indexPending')->name('indexPending');
//complete
Route::get('/complete/skbd', 'PembuatanController@completeSkbd')->name('completeSkbd');
Route::get('/complete/pktp', 'PembuatanController@completePktp')->name('completePktp');
Route::get('/complete/skl', 'PembuatanController@completeSkl')->name('completeSkl');
Route::get('/complete/sksm', 'PembuatanController@completeSksm')->name('completeSksm');
Route::get('/complete/skksi', 'PembuatanController@completeSkksi')->name('completeSkksi');
Route::get('/complete/skk', 'PembuatanController@completeSkk')->name('completeSkk');
Route::get('/complete/skbm', 'PembuatanController@completeSkbm')->name('completeSkbm');
Route::get('/complete/skd', 'PembuatanController@completeSkd')->name('completeSkd');
Route::get('/complete/spp', 'PembuatanController@completeSpp')->name('completeSpp');
Route::get('/complete/sku', 'PembuatanController@completeSku')->name('completeSku');
Route::get('/complete/skdu', 'PembuatanController@completeSkdu')->name('completeSkdu');
Route::get('/complete/skdmt', 'PembuatanController@completeSkdmt')->name('completeSkdmt');
Route::get('/complete/sktm', 'PembuatanController@completeSktm')->name('completeSktm');
//cetak surat
Route::get('/buat/cetak/skbd/{id}', 'PembuatanController@cetakSkbd')->name('cetakSkbd');
Route::get('/buat/cetak/pktp/{id}', 'PembuatanController@cetakPktp')->name('cetakPktp');
Route::get('/buat/cetak/skl/{id}', 'PembuatanController@cetakSkl')->name('cetakSkl');
Route::get('/buat/cetak/sksm/{id}', 'PembuatanController@cetakSksm')->name('cetakSksm');
Route::get('/buat/cetak/skksi/{id}', 'PembuatanController@cetakSkksi')->name('cetakSkksi');
Route::get('/buat/cetak/skk/{id}', 'PembuatanController@cetakSkk')->name('cetakSkk');
Route::get('/buat/cetak/skbm/{id}', 'PembuatanController@cetakSkbm')->name('cetakSkbm');
Route::get('/buat/cetak/skd/{id}', 'PembuatanController@cetakSkd')->name('cetakSkd');
Route::get('/buat/cetak/spp/{id}', 'PembuatanController@cetakSpp')->name('cetakSpp');
Route::get('/buat/cetak/sku/{id}', 'PembuatanController@cetakSku')->name('cetakSku');
Route::get('/buat/cetak/skdu/{id}', 'PembuatanController@cetakSkdu')->name('cetakSkdu');
Route::get('/buat/cetak/skdmt/{id}', 'PembuatanController@cetakSkdmt')->name('cetakSkdmt');
Route::get('/buat/cetak/sktm/{id}', 'PembuatanController@cetakSktm')->name('cetakSktm');
//cetak laporan
Route::get('/cetak', 'PembuatanController@completeCetak')->name('completeCetak');
//warga
Route::get('/buat/{id}', 'PembuatanController@getBuat')->name('getBuat');
Route::post('/buat/{id}/surat', 'PembuatanController@postBuat')->name('postBuat');
Route::get('/riwayat', 'PembuatanController@riwayatBuat')->name('riwayatBuat');
Route::get('/daftarbuat', 'PembuatanController@listBuat')->name('listBuat');
Route::get('/daftarbuat/{id}/detail', 'PembuatanController@detailBuat')->name('detailBuat');
Route::post('/daftarbuat/{id}/cancel', 'PembuatanController@cancelBuat')->name('cancelBuat');

Route::group(['middleware' => ['auth', 'role:Warga']], function () {
	//
});

Route::get('/tes', function () {
    return view('pdf.tostes');
});

//LAPORAN
Route::get('/laporan', 'LaporanController@index');
Route::get('/laporan/create', 'LaporanController@create');

Route::get('/lap-fpktp', function () {
    return view('laporan.fpktp');
});
Route::get('/lap-skbd', function () {
    return view('laporan.skbd');
});
Route::get('/lap-skbm', function () {
    return view('laporan.skbm');
});
Route::get('/lap-skd', function () {
    return view('laporan.skd');
});
Route::get('/lap-skdmt', function () {
    return view('laporan.skdmt');
});
Route::get('/lap-skdu', function () {
    return view('laporan.skdu');
});
Route::get('/lap-skk', function () {
    return view('laporan.skk');
});
Route::get('/lap-skksi', function () {
    return view('laporan.skksi');
});
Route::get('/lap-skl', function () {
    return view('laporan.skl');
});
Route::get('/lap-sksm', function () {
    return view('laporan.sksm');
});
Route::get('/lap-sktm', function () {
    return view('laporan.sktm');
});
Route::get('/lap-sku', function () {
    return view('laporan.sku');
});
Route::get('/lap-spp', function () {
    return view('laporan.spp');
});

// FORMS
Route::get('/fpktp', function () {
    return view('forms.f-permohonanKTP');
});

Route::get('/skk', function () {
    return view('forms.s-kematian');
});

Route::get('/skbm', function () {
    return view('forms.sk-belumMenikah');
});

Route::get('/skd', function () {
    return view('forms.sk-domisili');
});

Route::get('/skdmt', function () {
    return view('forms.sk-domisiliMT');
});

Route::get('/skdu', function () {
    return view('forms.sk-domisiliUsaha');
});

Route::get('/skl', function () {
    return view('forms.sk-kelahiran');
});

Route::get('/skksi', function () {
    return view('forms.sk-kematianSuamiOrIstri');
});

Route::get('/sksm', function () {
    return view('forms.sk-sudahMenikah');
});

Route::get('/sku', function () {
    return view('forms.sk-usaha');
});

Route::get('/skbd', function () {
    return view('forms.skbd');
});

Route::get('/sktm', function () {
    return view('forms.sktm');
});

Route::get('/spp', function () {
    return view('forms.sp-perkawinan');
});

resources/views/buatsurat.blade.php
@extends('partials.master')

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
      <div class="container-fluid">
            <div class="row mb-2">
                  <div class="col-sm-6">
                        <h1>{{$surat->nm_surat}}</h1>
                        <small>Tanggal: {{ $date->format('d M Y') }}</small>
                  </div>
            </div>
      </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<div class="container">
      <div class="container">
            <div class="card card-info">
                  <div class="card-header bg-warning">
                        <h3 class="card-title">Isi Data dengan Benar dan Sesuai</h3>
                  </div>
                  <!-- /.card-header -->
                  <!-- form start -->
                  <form class="form-horizontal" method="POST" action="{{ route('postBuat', $surat->id) }}" enctype="multipart/form-data">
                  @csrf
                  <input type="hidden" name="surat_id" value="{{ $surat->id }}">
                  <input type="hidden" name="user_id" value="{{ Auth::id() }}">
                  
                        <div class="card-body">
                        @if (($surat->id) == 1)
                              <center>Isi lampiran Pengantar RT/RW di bawah.</center>
                        @elseif (($surat->id) == 2)
                              <center>Isi lampiran Pengantar RT/RW di bawah.</center>
                        @elseif (($surat->id) == 3)
                              <center>Pastikan kamu sudah mengisi data <u>Pasangan</u> dan <u>Anak</u> di Profilmu.</center>
                              <label for="nm_anak" class="col-sm-2 col-form-label pt-3">Pilih Data Anak</label>
                              <div class="col-sm-3">
                                    <select name="nm_anak" required class="form-control @error('nm_anak') is-invalid @enderror" {{ count($nm_anak) == 0 ? 'disabled' : '' }}>
                                          @if(count($nm_anak) == 0)							
                                                <option>--Pilihan tidak ada--</option>
                                          @else											
                                                <option value="">--Silakan Pilih--</option>				
                                                @foreach($nm_anak as $value) 			
                                                      <option value="{{ $value->id }}">{{ $value->nm_anak }}</option>
                                                @endforeach
                                          @endif	
                                    </select>
                                    <span class="text-danger">@error('nm_anak') {{ $message }} @enderror</span>
                              </div>
                        @elseif (($surat->id) == 4)
                              <center>Pastikan kamu sudah mengisi data Pasangan di Profilmu.</center>
                        @elseif (($surat->id) == 5)
                              <center>Pastikan kamu sudah mengisi data Pasangan di Profilmu.</center>
                              <center>Dan telah mengisi kolom untuk file sk. kematian, tempat meninggal, dan tanggal meninggal pasangan.</center>
                        @elseif (($surat->id) == 6)
                              <center>Pastikan kamu sudah mengisi data Kematian di Profilmu.</center>
                              <label for="nm_alm" class="col-sm-2 col-form-label pt-3">Pilih Data Kematian</label>
                              <div class="col-sm-3">
                                    <select name="nm_alm" required class="form-control @error('nm_alm') is-invalid @enderror" {{ count($nm_alm) == 0 ? 'disabled' : '' }}>
                                          @if(count($nm_alm) == 0)							
                                                <option>--Pilihan tidak ada--</option>
                                          @else											
                                                <option value="">--Silakan Pilih--</option>				
                                                @foreach($nm_alm as $value) 			
                                                      <option value="{{ $value->id }}">{{ $value->nm_alm }}</option>
                                                @endforeach
                                          @endif	
                                    </select>
                                    <span class="text-danger">@error('nm_alm') {{ $message }} @enderror</span>
                              </div>
                        @elseif (($surat->id) == 7)
                              <center>Pastikan kamu sudah mengisi data Ayah di Profilmu.</center>
                        @elseif (($surat->id) == 8)
                              <div class="form-group row">Domisili saat ini: </div>
                              <!-- Alamat Domisili -->
                              <div class="form-group row">
                                    <label for="alamat_dom" class="col-sm-2 col-form-label">Alamat Domisili</label>
                                    <div class="col-sm-10">
                                          <input type="text" class="form-control @error ('alamat_dom') is-invalid @enderror" id="alamat_dom" placeholder="Alamat Domisili" name="alamat_dom">
                                          <input type="text" class="form-control" placeholder="Desa Sasakpanjang Kec. Tajurhalang Kab. Bogor" disabled="">
                                    </div>
                              </div>
                        @elseif (($surat->id) == 9)
                              <center>Pastikan kamu sudah mengisi data Ibu dan Ayah di Profilmu.</center>
                              <!-- Nama Suami/Istri -->
                              <div class="form-group row" style="padding: 20px 0px 0px 0px;">
                                    <label for="mantan_sutri" class="col-sm-2 col-form-label">Nama Mantan Suami/Istri</label>
                                    <div class="col-sm-10">
                                          <input type="text" class="form-control @error ('mantan_sutri') is-invalid @enderror" name="mantan_sutri" id="mantan_sutri" placeholder="Nama Mantan Suami/Istri">
                                          <small class="text-info">Kosongkan jika tidak memiliki.</small>
                                    </div>
                              </div>
                        @elseif (($surat->id) == 10)
                              <!-- <div class="form-group row">Isi data berikut dengan benar!</div> -->
                              <!-- Jenis Usaha -->
                              <div class="form-group row">
                                    <label for="jns_ush" class="col-sm-2 col-form-label">Jenis Usaha</label>
                                    <div class="col-sm-10">
                                          <input type="text" class="form-control @error ('jns_ush') is-invalid @enderror" id="jns_ush" placeholder="Jenis Usaha" name="jns_ush">
                                    </div>
                              </div>
                              <!-- Alamat Usaha -->
                              <div class="form-group row">
                                    <label for="alamat_ush" class="col-sm-2 col-form-label">Alamat Usaha</label>
                                    <div class="col-sm-10">
                                          <input type="text" class="form-control @error ('alamat_ush') is-invalid @enderror" id="alamat_ush" placeholder="Alamat Usaha" name="alamat_ush">
                                          <input type="text" class="form-control" placeholder="Desa Sasakpanjang Kec. Tajurhalang Kab. Bogor" disabled="">
                                    </div>
                              </div>
                        @elseif (($surat->id) == 11)
                              <center>Pastikan kamu sudah mengisi data Perusahaan di Profilmu.</center>
                        @elseif (($surat->id) == 12)
                              <center>Pastikan kamu sudah mengisi data Majlis Taklim di Profilmu.</center>
                        @else
                              <!-- Keperluan -->
                              <div class="form-group row">
                                    <label for="kpr_sktm" class="col-sm-2 col-form-label">Keperluan</label>
                                    <div class="col-sm-10">
                                          <input type="text" class="form-control @error ('kpr_sktm') is-invalid @enderror" id="kpr_sktm" name="kpr_sktm" placeholder="Keperluan">
                                    </div>
                              </div>
                        @endif
                        <hr>
                        <div class="form-group row" style="padding: 20px 0px 0px 0px;">Lampiran: </div>

                              <!-- Pengantar RT/RW -->
                              <div class="form-group row">
                                    <label for="file_rtrw" class="col-sm-2 col-form-label">Pengantar RT/RW</label>
                                    <div class="custom-file col-sm-7">
                                          <input type="file" class="form-control custom-file-input @error ('file_rtrw') is-invalid @enderror" id="file_rtrw" name="file_rtrw" required autofocus>
                                          <label class="custom-file-label">Pilih file</label>
                                          @error('file_rtrw')
                                                <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                                </span>
                                          @enderror
                                    </div>
                              </div>

                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                              <button type="submit" class="btn btn-success float-right">Submit</button>
                        </div>
                        <!-- /.card-footer -->
                  </form>
            </div>
      </div>
</div>
<!-- /.content -->
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/landing.blade.php
<!DOCTYPE html>
<html lang='en'>

<head>
      <meta class="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <title>SPSO Desa Sasakpanjang</title>
      <link rel="shortcut icon" href="{{ asset('/adminlte/dist/img/Kabupaten Bogor 160x160.png') }}">
      <!-- Don't forget to add your metadata here -->
      <link rel='stylesheet' href="{{ asset('/evie/css/style.min.css')}}" />

</head>

<body>
      <!-- Hero(extended) navbar -->
      <div class="navbar navbar--extended">
            <nav class="nav__mobile"></nav>
            <div class="container">
                  <div class="navbar__inner">
                        <a href="{{ url('landing') }}" class="navbar__logo">
                              <span style="display: inline-block; margin-top: 10px;"><img src="{{ asset('/evie/images/s.png')}}" alt="Kabupaten Bogor Logo" class="brand-image" style="height: 35px;"></span>
                              <!-- <span style="display: block;">Desa</span> -->
                        </a>
                        <nav class="navbar__menu">
                              <ul>
                              @guest
                                    <li><a onclick="return kontak()" href="#kontak">Kontak</a></li>
                                    <li><a href="{{ route('login') }}">Masuk</a></li>
                                    @if (Route::has('register'))
                                    <li class="nav-item">
                                          <a href="{{ route('register') }}">Registrasi</a>
                                    </li>
                                    @endif
                              @else
                                    <!-- <li><a href="{{ route('warga.show', Auth::user()->id) }}">{{ ucfirst(Auth::user()->name) }}</a></li> -->
                                    @if (Auth::user()->warga != NULL)
                                          <li><a href="{{ url('dashboardw') }}">{{ ucfirst(Auth::user()->name) }}</a></li>
                                    @elseif (Auth::user()->role->firstWhere('id', 1))
                                          <li><a href="{{ url('dashboard') }}">{{ ucfirst(Auth::user()->name) }}</a></li>
                                    @else 
                                          <li><a href="{{ url('dashboarda') }}">{{ ucfirst(Auth::user()->name) }}</a></li>
                                    @endif
                                    
                                    <li class="nav-item">
                                          <a class="dropdown-item" href="{{ route('logout') }}"
                                          onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();">
                                                {{ __('Logout') }}
                                          </a>
                                          <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                                @csrf
                                          </form>
                                    </li>
                              @endguest
                              </ul>
                        </nav>
                        <div class="navbar__menu-mob"><a href="" id='toggle'><svg role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                                          <path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z" class=""></path>
                                    </svg></a></div>
                  </div>
            </div>
      </div>
      <!-- Hero unit -->
      <div class="hero">
            <div class="hero__overlay hero__overlay--gradient"></div>
            <div class="hero__mask"></div>
            <div class="hero__inner">
                  <div class="container">
                        <div class="hero__content">
                              <div class="hero__content__inner" id='navConverter'>
                        @guest
                                    <h1 class="hero__title">Selamat Datang di Pembuatan Surat <i>Online</i> Desa Sasakpanjang</h1>
                        @else
                              @if (Auth::user()->warga != NULL)
                                    <h1 class="hero__title">Haloo {{ ucfirst(Auth::user()->name) }}, Selamat Datang di Pembuatan Surat <i>Online</i> Desa Sasakpanjang</h1>
                                    <a href="{{ url('choose')}}" class="button button__accent">Dapatkan Surat</a>
                              @else 
                                    <h1 class="hero__title">Haloo Admin, Selamat Datang di Pembuatan Surat <i>Online</i> Desa Sasakpanjang</h1>
                                    <a href="#" class="button button__accent">Haloo Admin..</a>      
                              @endif      
                        @endguest

                              
                                    
                              
                                    
                              </div>
                        </div>
                  </div>
            </div>
      </div>
      <div class="hero__sub">
            <span id="scrollToNext" class="scroll">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" class='hero__sub__down' fill="currentColor" width="512px" height="512px" viewBox="0 0 512 512" style="enable-background:new 0 0 512 512;" xml:space="preserve">
                        <path d="M256,298.3L256,298.3L256,298.3l174.2-167.2c4.3-4.2,11.4-4.1,15.8,0.2l30.6,29.9c4.4,4.3,4.5,11.3,0.2,15.5L264.1,380.9c-2.2,2.2-5.2,3.2-8.1,3c-3,0.1-5.9-0.9-8.1-3L35.2,176.7c-4.3-4.2-4.2-11.2,0.2-15.5L66,131.3c4.4-4.3,11.5-4.4,15.8-0.2L256,298.3z" />
                  </svg>
            </span>
      </div>
      <!-- Steps -->
      <div class="steps landing__section">
            <div class="container">
                  <p class="text-center">Situs <i>web</i> khusus untuk warga Desa Sasakpanjang dalam mengajukan pembuatan surat secara <i>online</i>. </p>
                  <h2>Bagaimana prosedur mendapat surat melalui <i>website</i>?</h2>
                  <p>Berikut cara mendapatkan surat yang diinginkan.</p>
            </div>
            <div class="container">
                  <div class="steps__inner">
                        <div class="step">
                              <div class="step__media">
                                    <img src="{{ asset('/evie/images/undraw_designer.svg')}}" class="step__image">
                              </div>
                              <h4>Jenis Surat</h4>
                              <p class="step__text">Pemohon memilih jenis surat yang akan dibuat.</p>
                        </div>
                        <div class="step" style="background-color: #f7f7f7;">
                              <div class="step__media">
                                    <img src="{{ asset('/evie/images/undraw_responsive.svg')}}" class="step__image">
                              </div>
                              <h4>Data Diri</h4>
                              <p class="step__text">Isi data diri dengan benar sesuai jenis surat yang dipilih. </p>
                        </div>
                        <div class="step">
                              <div class="step__media">
                                    <img src="{{ asset('/evie/images/undraw_Mail_sent.svg')}}" class="step__image">
                              </div>
                              <h4> Pemberitahuan</h4>
                              <p class="step__text">Pemberitahuan surat yang diinginkan akan dikirim melalui akun pemohon. </p>
                        </div>
                        <div class="step" style="background-color: #f7f7f7;">
                              <div class="step__media">
                                    <img src="{{ asset('/evie/images/undraw_creation.svg')}}" class="step__image">
                              </div>
                              <h4>Dapat Surat</h4>
                              <p class="step__text">Setelah mendapat pemberitahuan, warga dipersilahkan datang ke kantor desa serta membawa KTP asli pemohon untuk validasi diri pemohon. </p>
                        </div>
                  </div>
            </div>
      </div>
      <!-- Expanded sections -->
      <div class="expanded landing__section">
            <div class="container">
                  <div class="expanded__inner">
                        <div class="expanded__media">
                              <img src="{{ asset('/evie/images/undraw_browser.svg')}}" class="expanded__image">
                        </div>
                        <div class="expanded__content">
                              <h2 class="expanded__title">Jenis pelayanan surat di Desa Sasakpanjang</h2>
                              <p class="expanded__text">Formulir Permohonan KTP, Surat Kematian, Surat Keterangan Belum Menikah, Surat Keterangan Bersih Diri, Surat Keterangan Domisili Majlis Taklim, Surat Keterangan Tidak Mampu, Surat Keterangan Domisili Usaha, Surat Keterangan Domisili, Surat Keterangan Kelahiran, Surat Keterangan Kematian Suami-Istri, Surat Keterangan Sudah Menikah, Surat Keterangan Usaha, Surat Pengantar Perkawinan.</p>
                        </div>
                  </div>
            </div>
      </div>
      <div class="expanded landing__section">
            <div class="container">
                  <div class="expanded__inner">
                        <div class="expanded__media">
                              <img src="{{ asset('/evie/images/undraw_online_resume.svg')}}" class="expanded__image">
                        </div>
                        <div class="expanded__content">
                              <h2 class="expanded__title">Mengapa memilih pelayanan pembuatan surat secara <i>online</i>? </h2>
                              <p class="expanded__text">1. Warga tidak perlu antri untuk mendapat surat yang diinginkan.</p>
                              <p class="expanded__text">2. Efisiensi pelayanan surat di Desa Sasakpanjang.</p>
                              <p class="expanded__text">3. Dapat mengurangi kerumunan di kantor desa untuk mencegah penyebaran COVID-19.</p>
                        </div>
                  </div>
            </div>
      </div>
      <div class="expanded landing__section">
            <div class="container">
                  <div class="expanded__inner">
                        <div class="expanded__media">
                              <img src="{{ asset('/evie/images/together.svg')}}" class="expanded__image">
                        </div>
                        <div class="expanded__content">
                              <h2 class="expanded__title">Sistem Usulan Berupa Prototype Untuk Tugas Akhir</h2>
                              <p class="expanded__text">Aplikasi berbasis <i>website</i> untuk keperluan sistem informasi administrasi kependudukan khusus untuk pembuatan surat warga Desa Sasakpanjang</p>
                        </div>
                  </div>
            </div>
      </div>

      <!-- Footer -->
      <div class="footer footer--dark">
            <div class="container">
                  <div class="footer__inner" id="kontak">
                        <p class="footer__textLogo">Kontak kami</p>
                        <div class="footer__data">
                              <div class="footer__data__item">
                                    <div class="footer__row">
                                          <b>Alamat Kantor Desa</b>
                                    </div>
                                    <div class="footer__row">
                                          Jl. AMD RT.01/08 Desa Sasakpanjang Desa Sasakpanjang Kecamatan Tajurhalang Kabupaten Bogor Provinsi Jawa Barat, 16320
                                    </div>
                              </div>
                        </div>
                  </div>
            </div>
            <script src="{{ asset('/evie/js/app.min.js')}}"></script>

</body>

</html>